- locale/cz.yml
> Fixed some bad translates

- locale/cz.yml
> Fixed bad Grammar

- locale/cz.yml
Add an optional extended description...
> Translated

- locale/cz.yml
Add an optional extended description...
> Translated signs and some small grammar fixes

- locale/cz.yml
Add an optional extended description...
> Next translate

- locale/cz.yml
Add an optional extended description...
> Translated new things

- locale/cz.yml
Can't wait to another. :D
Amazing work!
> Next transates

- locale/cz.yml
> [1.0.2] Translated!

- locale/cz.yml
> Translated!

- locale/cz.yml
> HYPE [1.1.6 translate]

- locale/cz.yml
> [1.1.7] Translated new things

- locale/cz.yml
> [1.1.9] Translated Czech locale

- locale/cz.yml
Fixed some stuff and added Wall translate
> [1.1.14] Protection Wall translate

- locale/cz.yml
Spectator translate and grammar fix for Stats
> [1.1.14] Spectator translate

- locale/cz.yml
> [1.2.1] Translated

- locale/cz.yml
Wohoo! Another translate from me :3
> [1.2.2] Translated some locale

- src/io/github/yannici/bedwars/Shop/Specials/TNTSheep.java
Sheep would go to a random enemy from the other team. Now they will follow the closest enemy to the player who activated the sheep.
> [1.2.3] Fixes sheep selecting the wrong target

- locale/cz.yml
> [1.2.3] New features CZ translate

- src/io/github/yannici/bedwars/Listener/EntityListener.java
> [1.2.8] AntiAura compatibility

- locale/cz.yml
- locale/de.yml
- locale/en.yml
- locale/fr.yml
- locale/pt.yml
- locale/ru.yml
- locale/sk.yml
- src/io/github/yannici/bedwars/Game/Game.java
- src/io/github/yannici/bedwars/Game/GameLobbyCountdown.java
- src/io/github/yannici/bedwars/Main.java
- src/io/github/yannici/bedwars/Updater/ConfigUpdater.java
resolves #285 
adds config ``lobbytime-full``, checks if waiting game reaches max-players, then decreases countdown to ``lobbytime-full`` (if it isn't yet lower than this value)
adds message ``X more players needed.`` when player joins a waiting game, so people know how many players to wait for until countdown starts (depending on countdown start rule)
> [1.2.8] Decrease countdown when full

- locale/de.yml
- locale/en.yml
- shop.yml
- src/io/github/yannici/bedwars/Shop/Specials/SpecialItem.java
- src/io/github/yannici/bedwars/Shop/Specials/Tracker.java
- src/io/github/yannici/bedwars/Shop/Specials/TrackerListener.java
resolves #354 
locally tested, build on jenkins succeeded, tests in production on my server worked fine.
> [1.2.8] Add compass as player tracker

- config.yml
- src/io/github/yannici/bedwars/Listener/ServerListener.java
resolves #308
to be honest: not really dry code, just copied and pasted existing methods.
locally tested, build on jenkins succeeded, tests in production on my server worked fine.
> [1.2.8] Add bungeecord MOTD placeholders

- src/io/github/yannici/bedwars/Listener/PlayerListener.java
includes spectator chat in endgame when ``global-chat-after-end`` is ``true``
also fixes #341
> [1.2.8] possibility to include spectator chat in endgame

- src/io/github/yannici/bedwars/Listener/EntityListener.java
resolves #379 
just added ``Main.getInstance().getServer().getPluginManager().isPluginEnabled("AAC")`` in lines 166 and 192
I think this small change can be merged without our little workflow, @Yannici :)
> [1.2.8] Add AAC compatibility

- src/io/github/yannici/bedwars/Shop/Specials/Tracker.java
fixes #389 
Shouldn't need testing by anyone else since it is just a few lines of code being changed.
> [1.2.8] Player Tracker needs to be in Inventory to track players #389

- src/io/github/yannici/bedwars/Game/Game.java
> [1.2.8] fix remove team command

- .gitignore
- build.xml
- src/io/github/yannici/bedwars/Game/BungeeGameCycle.java
- src/io/github/yannici/bedwars/Game/Game.java
- src/io/github/yannici/bedwars/Game/PlayerStorage.java
- src/io/github/yannici/bedwars/Listener/HangingListener.java
- src/io/github/yannici/bedwars/Listener/Player18Listener.java
- src/io/github/yannici/bedwars/Listener/PlayerListener.java
- src/io/github/yannici/bedwars/Main.java
Build http://ci.sebastianbinder.com/job/Bedwars-Rel/24/artifact/dist/BedwarsRel-1.2.8-56411ebd47ee638879539b6b4ff3cba6f88c79d8.jar is based on this branch. So everything can be tested again before final merge. As long as there aren't any major bugs coming up now, this branch is ready to be merged into master branch. This shall be the final 1.2.8 release - any other bugs should be fixed in upcoming version 1.2.9 then.
fixes #233
fixes #239 
fixes #275
fixes #335 
fixes #369 
fixes #384 
@Yannici @Granik24 @Block-Build - is that okay for all of you?
> [1.2.8] Release

- src/io/github/yannici/bedwars/Game/Game.java
- src/io/github/yannici/bedwars/Listener/Player18Listener.java
Fixes issues concerning player joining server and player joining game if not on Bungeecord.
Should fix #432 and #433 
Build for testing: http://ci.sebastianbinder.com/job/Bedwars-Rel/34/artifact/dist/BedwarsRel-1.2.8-82417b96ede8897b1039d6109b2cc7a2c505819c.jar
> [1.2.8-p1] Fix Player Spawn Location if not Bungeecord

- src/io/github/yannici/bedwars/Shop/Specials/ProtectionWallListener.java
> Default Block don't become ProtectionWall Issue - #445

- src/main/resources/locale/nl.yml
> [1.3.0] Dutch Language

- src/main/java/io/github/yannici/bedwars/Listener/PlayerListener.java
- src/main/java/io/github/yannici/bedwars/Updater/ConfigUpdater.java
> [1.3.1] Chat Format

- src/main/java/io/github/yannici/bedwars/Listener/PlayerListener.java
> [1.3.1] Ressource Pickup

- src/main/java/io/github/yannici/bedwars/Com/v1_9_R1/TNTSheep.java
- src/main/java/io/github/yannici/bedwars/Game/PlayerStorage.java
- src/main/java/io/github/yannici/bedwars/Game/Region.java
- src/main/java/io/github/yannici/bedwars/Game/RessourceSpawner.java
- src/main/java/io/github/yannici/bedwars/Listener/PlayerListener.java
- src/main/java/io/github/yannici/bedwars/Shop/Specials/MagnetShoe.java
- src/main/java/io/github/yannici/bedwars/Shop/Specials/RescuePlatformListener.java
- src/main/java/io/github/yannici/bedwars/Utils.java
- src/main/java/io/github/yannici/bedwars/Villager/MerchantCategory.java
> [1.3.1] Could fix tnt sheep with newer spigot builds

- src/main/java/io/github/yannici/bedwars/Listener/BlockListener.java
- src/main/java/io/github/yannici/bedwars/Listener/PlayerListener.java
> [1.3.1] Fixes and Quit Message

- src/main/java/io/github/yannici/bedwars/Listener/PlayerListener.java
> Change addInventory

- pom.xml
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/ParticleSpawner.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/PathfinderGoalBedwarsPlayer.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/PerformRespawnRunnable.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/SpawnEgg1_9.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/TNTSheep.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/TNTSheepRegister.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/Title.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/VillagerItemShop.java
> [1.3.1] Add Spigot 1.9.4 compatibility

- src/main/java/io/github/yannici/bedwars/Updater/ConfigUpdater.java
Hey @Yannici,
ein kleiner Fix zu https://www.spigotmc.org/threads/bedwars-rel.64797/page-69#post-1578223
Theoretisch sollte man das doch direkt in den Master mergen, das Projekt neu auf Jenkins bauen und dann beim Release ersetzen können, oder?
> [1.3.1] Shop Hotfix

- src/main/java/io/github/yannici/bedwars/Com/v1_8_R1/VillagerItemShop.java
- src/main/java/io/github/yannici/bedwars/Com/v1_8_R2/VillagerItemShop.java
- src/main/java/io/github/yannici/bedwars/Com/v1_8_R3/VillagerItemShop.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R1/VillagerItemShop.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/VillagerItemShop.java
- src/main/java/io/github/yannici/bedwars/Shop/NewItemShop.java
- src/main/java/io/github/yannici/bedwars/Utils.java
- src/main/java/io/github/yannici/bedwars/Villager/MerchantCategory.java
Add teamcolored shopitems for oldshop
Add colored categorys in new shop
Add colored CARPET
Add colored STAINED_GLASS_PANE
Issue #552
> Improve colored blocks in Shop

- src/main/java/io/github/yannici/bedwars/Updater/ConfigUpdater.java
> [1.3.2] Fix sound versions

- src/main/java/io/github/yannici/bedwars/Com/v1_10_R1/ActionBar.java
- src/main/java/io/github/yannici/bedwars/Com/v1_8_R1/ActionBar.java
- src/main/java/io/github/yannici/bedwars/Com/v1_8_R2/ActionBar.java
- src/main/java/io/github/yannici/bedwars/Com/v1_8_R3/ActionBar.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R1/ActionBar.java
- src/main/java/io/github/yannici/bedwars/Com/v1_9_R2/ActionBar.java
- src/main/java/io/github/yannici/bedwars/Game/Game.java
- src/main/java/io/github/yannici/bedwars/Updater/ConfigUpdater.java
- src/main/resources/config.yml
> [1.3.3] Possibility to show teamname in ActionBar

- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/Game.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/PlayerSettings.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Listener/PlayerListener.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/NewItemShop.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Updater/ConfigUpdater.java
- src/main/resources/config.yml
A option to configure the default shop
#596
> add default shop

- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/GameCycle.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/ProtectionWall.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/ProtectionWallListener.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/RescuePlatform.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/RescuePlatformListener.java
Fix #594 
Also fix the delay on walls.
> 1.3.3 rescue/wall delay bug

- src/main/java/io/github/bedwarsrel/BedwarsRel/Villager/ItemStackParser.java
> fix enchant paser

- pom.xml
- src/main/java/io/github/bedwarsrel/BedwarsRel/Listener/PlayerListener.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/ProtectionWall.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/RescuePlatform.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/RescuePlatformListener.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/SpecialItem.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/TNTSheep.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/TNTSheepListener.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/WarpPowder.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Shop/Specials/WarpPowderListener.java
Fix left hand problems with specialitems
> 1.3.3 use special item

- src/main/java/io/github/bedwarsrel/BedwarsRel/Commands/AddHoloCommand.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Main.java
- src/main/resources/locale.yml
> add dependency notification #626

- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/Game.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/PlayerStorage.java
> [1.3.4] ressource spawner delay

- src/main/java/io/github/bedwarsrel/BedwarsRel/Commands/JoinGameCommand.java
> Join Random Game

- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/PlayerStorage.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Updater/ConfigUpdater.java
- src/main/resources/config.yml
> [1.3.4] save-inventory

- src/main/java/io/github/bedwarsrel/BedwarsRel/Game/RessourceSpawner.java
- src/main/java/io/github/bedwarsrel/BedwarsRel/Updater/ConfigUpdater.java
- src/main/resources/config.yml
> Ressource spawn in chest

- common/src/main/java/io/github/bedwarsrel/statistics/PlayerStatisticManager.java
> [1.3.7] Fix NPE
